plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.android.junit5 apply false
}

Properties properties = new Properties()
properties.load(project.rootProject.file("local.properties").newDataInputStream())

//apply signing config
apply from: rootProject.file(properties.getProperty("keystore.signing"))

project.ext {
    minSdk = 24
    targetSdk = 36
    compileSdk = 37
    keystore = rootProject.file(properties.getProperty("keystore"))
}

apply from: "gradle/release-artifacts.gradle"

apply from: "gradle/module-defaults.gradle"