plugins {
    alias libs.plugins.android.application
}

packageName = "org.eu.thedoc.zettelnotes.buttons.telegraph"

dependencies {
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson

    implementation libs.flexmark
    implementation libs.flexmark.ext.gfm.tasklist
    implementation libs.flexmark.ext.gfm.strikethrough
    implementation libs.flexmark.ext.tables

    implementation libs.gson
}
